menu:
    Blog: /
    Archive: /archives/
    Slide: /categories/slide/
    GitHub: https://github.com/georgeteo
    Resume: https://www.linkedin.com/in/georgeteo/

favicon: /favicon.ico
logo: /favicon.png

# Comment
# disqus: wicksome
# duoshuo:
# cloudTie:

# Analytics
# google-analytics:
# ga: UA-43444044-3

# Adsense
# google-adsense:
# gad:
#     client: ca-pub-2402079508512433
#     slot: 9218385844

# Copyright Infomation
startyear: 2018
